function teste(){
    try {
        123    
    } catch (error) {
        console.log("Deu um erro " + error)
    }
    
}

teste()